### ISSUE TITLE
US - Store Details Page

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#10]
## Value proposition

As a user, 

i want to see the details of one single store in my list 

so i can see detailed information of the store

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/4272cbc4-5085-4967-b9f5-95fbca299692)

## Acceptance criteria

- [ ] Clicking on one store opens the details page with the store name as the title
- [ ] If a store has a note, the note is displayed
- [ ] A click on the “back to list” button returns to the list of all stores

## Tasks

- [ ] Add the key `note` to the objects in the stores array
- [ ] For each store in the list, add a Link-element to the /stores/$[id].js file.
- [ ] Create the /stores/[id].js file, use the router to get the [id] from the query and find the store from the “stores” array. Return the store information and a “back to list” link.

**Comment by Roland-Hufnagel** [comment]
Clear and good Userstory 💪
