### ISSUE TITLE
US - List of Stores

### ISSUE THREAD

**Issue by lennart-kaminsky** [GoekhanAgkurt/capstone-grocery-app#11]
## Value proposition

As a user seeking a more organized shopping experience,
I want to seamlessly navigate between an "Product List" page and a "Store List" page with a static list of stores
so I can switch between my two main pages “Products” and “Stores” in order to plan my shopping trips efficiently.

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/120521307/ecab20b4-a2bb-4f39-b170-6f49c441a5bb)

## Acceptance criteria

- [x] There should be a navigation bar at the bottom of the app with two tabs with icons for the “Product list page” and “Store list page”.
- [x] On the "Store list page" is the title "Store list" and a list of all available stores
- [x] Clicking the “Product List” tab should navigate the user to the page displaying the list of grocery items.
- [x] Clicking the “Store List” tab should navigate the user to a page displaying a static list of stores.
- [x] The active page should be highlighted in the navigation bar.

## Tasks

- [x] Inside the pages folder create a new file that renders the store list page.
- [x] Create a component “Navigation” and render it in the “_app.js” file.
- [x] Inside the Navigation component, render two Links to the "Product list page" and "Store list page".
- [x] Highlight the current Link by getting the active page with the help of the `router.pathname` function.
- [x] Create a component “StoreList” and map over the stores array to display each store name in a list.
