### ISSUE TITLE
US - Delete Store

### ISSUE THREAD

**Issue by GoekhanAgkurt** [GoekhanAgkurt/capstone-grocery-app#12]
## Value proposition

As a user

I want to delete an store from the app

In order to delete stores that i don’t want to include in my shopping trips anymore

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/78581683-1f66-40c2-8d7d-e1b242141c6d)

## Acceptance criteria

- [ ] The user can delete a store from the store list and from the store details page by clicking a delete icon.
- [ ] After clicking the delete icon, a confirmation message with a cancel or confirm button appear. When confirming, the store gets deleted. When canceling, the delete process is stopped. 
- [ ] The store list doesn’t display deleted stores
- [ ] When a product was linked to a store, the deleted store is removed from this product. The info for the product says: no store selected.

## Tasks

- [ ] Inside the stores page, write a `handleDeleteStore` function that updates the `stores` array to not contain the store to delete. 
- [ ] render the delete button in the store list and the store details page and try to reuse the existing `ComfirmDelete` component for the onSubmit of those delete icons.
- [ ] update the `products` array so the deleted store is removed from its previously linked products.

**Comment by feivlinus** [comment]
Nice User Story bro. Keep on doing such amazing stuff.

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/8994153/2d14219e-4962-4b1d-a3a1-8d4277db5c01)
