### ISSUE TITLE
US - Edit Store

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#13]
## Value proposition

As a user, 
I want to be able to edit the details of a specific store
so I can update and customize the name and details based on my preferences or changing needs.	

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/e5527049-7fee-4919-8c70-80cc0bb2f514)

## Acceptance criteria

- [ ] From the details page of a store, there is a visible edit button.
- [ ] Clicking the edit button opens a form to edit the store, that shows input fields where the user can modify the name and note of a store.
- [ ] The form should be pre-filled with the current details of the store to provide a starting point for editing. The name input field should be required.
- [ ] After editing, the user can click on a save button to apply the changes and brings the user back to the updated store details page.
- [ ] Users should have the option to cancel the editing process and go back to the previous store details page by clicking a cancel button.
- [ ] After editing a store name, the products that are connected to this store show the updated store on their details page.

## Tasks

- [ ] Inside the “/stores/[id].js” file, add an edit button that changes a state `isEdit` and renders a form to edit the store. Try to reuse the "add store" - form. The form should include: 
  - [ ] an input field for each detail with the existing value as defaultValue
  - [ ] a “Cancel” link back to the details page of the store
  - [ ] a “Submit” button which receives a “handleEditStore” function as the onSubmit value
- [ ] Write a “handleEditStore” function that takes an event and id as parameters and changes the name and note of the store with the given id of the “stores”-array in localStorage

**Comment by Roland-Hufnagel** [comment]
Hello Team Grocery. This looks very good to me 👍. 

I think you already have a form component for creating new shops. Do you want to reuse it for the edit-mode? If so please define it in the tasks.
