### ISSUE TITLE
US - Delete Product in Details Page

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#14]
## Value proposition

As a user that is always seeking for efficiency, 
I want to be able to delete a grocery product completely from my product list when I'm on the details page
so I can easily remove a product while seeing all the information.	

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/afcbbfe2-d7ee-4a0e-99bf-f61101b09512)

## Acceptance criteria

- [ ] On the details page of a grocery product, a clearly visible and accessible “Delete” button (with icon) is present
- [ ] Clicking the “Delete” button replaces the button with a Confirmation message and buttons with icons to confirm or cancel the delete process
- [ ] When clicking the confirm button the product will be deleted and the user will be redirected to the products list page which is not showing the deleted product anymore
- [ ] When clicking the cancel button the confirmation message and its buttons is replaced with the delete button again

## Tasks

- [ ] Inside the “/products/[id]/index.js” file
- [ ] add a “Delete” button that sets a state "showConfirmation" to true when being clicked
- [ ] add a confirmation div with the question "Delete the entire product?" and a cancel and confirm button that is styled in the same way as the delete button
  - [ ] Clicking the cancel button sets the "showConfirmation" state to false
  - [ ] Clicking the confirm button deletes the product from the array of products in the localStorage and the user gets redirected to the product list page
- [ ] conditionally render the delete button and confirmation div depending on the "showConfirmation" state (`display={showConfirmation}` or `display={!showConfirmation}`)

**Comment by JessicaLoers** [comment]
**Hello Grocery Tea, @luederb @lennart-kaminsky @GoekhanAgkurt**  ✌️

Your story focuses on the ability to delete a product from the details page. If the primary goal is to enhance the **deletion functionality itself** (regardless of where it is accessed), the story might need to be adjusted to emphasise the functionality rather than its location (details page). 
_I mention this because your approach is somewhat untypical - but hey, why not?_

**AC**
Attention: This is a super picky suggestion 😁

> - On the details page of a grocery product, a clearly visible and accessible “Delete” button (with icon ) is present

➡️ _Because you also do it with the Cancel and Delete buttons, you could mention here that the button has an icon._
