### ISSUE TITLE
US - List of Grocery Products

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#2]
## Value proposition

As a user, 
I want to see a list of all grocery products
so I can get an overview of all grocery items

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/c6fcf458-58f0-49d4-9bbd-8de6ee078a7b)

## Acceptance criteria

- [ ] the title of the home page is Grocery App
- [ ] on the home page, there is a list of all products with the title product List
- [ ] each product is listed with his name
- [ ] the products list is vertically scrollable

## Tasks

- [ ] Create the feature branch "products-list"
- [ ] Create the data.js inside the lib folder of your project.
- [ ] Inside the data.js, create an array of objects with example-products with the key-values pairs: name: "product-name"
- [ ] In the /_app.js file, create a localStorage State variable “products", that has the data.js - array as the initial value and drill the “products” state down to all pages
- [ ] Create a component “ProductsList” and map over the products array and put the “Product” component in the list - elements. The Product gets the prop product={product}.
- [ ] Create a component “Product”. Receive the prop {product} and return `<li> {product.name} </li>`

```

**Comment by JessicaLoers** [comment]
**Hi @luederb**  
nice first User Story✨

I only noticed one small thing. 

In the description there is a title _Grocery App_ and a headline _Item List_. 
These two UI elements should please be listed as an item in the AC.
