### ISSUE TITLE
US - Improved Icons and UI

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#25]
## Value proposition

As a user expecting a nice user flow and interface
I want to easily understand the icons and functionality of the app
so I can focus on efficiently planning my shopping trips.

## Description

Example Design: 
![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/7c68bb7b-42cd-446f-92b0-3eab7810ef98)

## Acceptance criteria

- [ ] The app has clean, simple and harmonious colors that support a good user experiences (e.g. contrast values for accessibility)
- [ ] Icons have a clear and easily understandable meaning.
- [ ] Same style (icon family) for all icons.
- [ ] The icons are nicely and reasonably positioned inside buttons or other areas and elements.
- [ ] Overlapping of any elements should be avoided or handled in a reasonable way.

## Tasks

- [ ] Define a global color schema
  - [ ] Pay attention to contrast and design 
  - [ ] collect all already used colors in global variables
- [ ] Choose one icon family
- [ ] Choose one method to integrate the icons
  - [ ] If using svg's, store and design them inside the project structure

**Comment by Philipp-Hess** [comment]
Hey nice Userstory!  go for it 👍
