### ISSUE TITLE
US - Create new Grocery Item

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#3]
## Value proposition

As a user, 
i want to add a new item and see it in the list of items
so i can create new items in the list of items

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/645060c7-fd03-4588-ab9d-245f8296287f)

## Acceptance criteria

- [ ] on the home page, there is a "+ Add new item" - Link that brings the user to a page with the title "Add an item"
- [ ] The user can insert the name of a new item and a note to that new item in the "Add an Item" form.
- [ ] The Submit button adds the new item to the items list and brings the user back to the updated "Items List" - page. The note is not displayed in the "Items List"
- [ ] The Cancel button returns to the "Items List" without adding a new item

## Tasks

- [ ] Create the feature branch "create-product"
- [ ] In the `/index.js`, return a Link  “+ Add new item” to the `/create.js` file
- [ ] Create the `/create.js` file and write a “handleAddProduct” function that 
  - [ ] receives the “event” parameter
  - [ ] gets the data from the event 
  - [ ] adds this parameter to the `products` state array. 
- [ ] Return
  - [ ] a form 
    - [ ] that has the property `onSubmit={handleAddProduct}`
    - [ ] a label "Item name"
    - [ ] input field to enter the new product name
    - [ ] a label "Add a note"
    - [ ] input field to enter the note for that item
  - [ ] a “Submit” Button
  - [ ] a “Cancel” - Link to the `/index.js` page

```

**Comment by onemanwenttomow** [comment]
> The Submit button adds the new item to the items list and brings the user back to the updated "Items List" - page. The note is not displayed in the "Items List"

Is "not" at typo? Should it be "now"?

Otherwise looks good to me. :)

**Comment by luederb** [comment]
Thanks 🙂
No, that's actually not a typo. The note of an item is only displayed in the item details page and not in the "list item" overview. We think that would clutter the list too much and would make it unreadable.
