### ISSUE TITLE
US - Search Products

### ISSUE THREAD

**Issue by lennart-kaminsky** [GoekhanAgkurt/capstone-grocery-app#32]
## Value proposition

As a user
I want to search for products in my product list
In order to quickly find my desired product

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/134974986/e8549ae0-6863-4b53-a0ea-16fa7a60a30c)

## Acceptance criteria

- [x] There is a searchbar of the top in the list
- [x] In the searchbar is a search icon and a placeholder
- [x] When typing in the search input, the product list gets filtered simultaneously 
- [x] When no product is found, a message appears to inform the user 

## Tasks

- [x] create a new branch "search-bar"
- [x] create a component called `SearchBar` wich handles the search functionality
- [x] add a icon into the search input field via icons component
- [x] add a message function, when there is no product found

**Comment by feivlinus** [comment]
LGTM! Good and clean user story. 👍
