### ISSUE TITLE
US - Add Store Location

### ISSUE THREAD

**Issue by lennart-kaminsky** [GoekhanAgkurt/capstone-grocery-app#33]
## Value proposition

As a User
I want to see the Location of a stores
In order to know or remember where I have to go

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/134974986/da83d797-4ce3-466c-abc4-7801e2d161c3)

## Acceptance criteria

- [ ] the address of the Store is displayed on the store details page
- [ ] a map is displayed with a location pin of the store location
- [ ] the location is editable
- [ ] when creating a store, a location can be added

## Tasks

- [ ] create a feature branch
- [ ] install and import all need leaflet plugins
- [ ] add the location key to the stores array in the data.js
- [ ] create a map component
- [ ] adjust the store details page (with the edit store form) and the create store page
- [ ] for adding a location convert the address into usable location coordinates for leaflet (e.g. via API)

**Comment by Roland-Hufnagel** [comment]
Looks fine 👍
