### ISSUE TITLE
US - Upload Product Picture

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#35]
## Value proposition

As a user
I want to add a personal picture to my product
So I can better remember, specify and identify the product when using the app

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/4a877bfb-1618-4279-bc19-6c8d7c16cdc1)

## Acceptance criteria

- [x] When creating or editing a product, the user can choose a personal picture for his product from his local files via the "upload image" button / icon on the top right of the product-image-placeholder. If the product already has a picture, the user can edit (re-upload) a picture via the "edit image" button / icon. 
- [x] After choosing the local file, the explorer / finder - window closes and the picture is displayed properly on top of the the product details page
- [x] The user can remove the chosen picture by clicking on the "remove" button / icon on the top left corner of the chosen picture.
- [x] After clicking the "Cancel" button while creating a new product, the user gets redirected to the product list, without adding the product to the list. 
- [x] Canceling the edit product process, brings the user back to the product details page, where only the placeholder picture is displayed.
- [x] The picture is finally saved to the product after clicking the "Submit" button at the end of the create form (or the "Save" button on the edit form).
- [x] When creating a new product without choosing a picture, a placeholder picture is displayed in the product details page.
- [ ] The user gets informed about upload errors (wrong file format etc.) and how to avoid them. 
- [x] Inform the user via a message or animation, once the upload process is started.

## Tasks

- [ ] create the feature branch "product-image"
- [ ] Implement cloudinary into your code
- [ ] add an "upload image" button in the create form and an "upload image" and "edit image" button in the edit form (conditionally). 
- [ ] For both forms, render the "remove image" button / icon when an image is already selected.
- [ ] Manage upload errors like wrong file formats by adding the attribute accept=".png, .jpeg, .jpg, .webp" to the image input element.
- [ ] Render a custom message for an upload error and give the user the information how to avoid the upload error. The message should be displayed after choosing the local image file.
- [ ] render a message or animation during the image upload process.

**Comment by Roland-Hufnagel** [comment]
Looks like a lot of work! Have fun 👍
