### ISSUE TITLE
US - Grocery Product Details Page

### ISSUE THREAD

**Issue by lennart-kaminsky** [GoekhanAgkurt/capstone-grocery-app#4]
## Value proposition

As a user
I want to see the details of one single grocery product in my list
so i can see detailed information of the product.

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/a2b3df0b-6148-45c8-be00-b16eb4ff1990)

## Acceptance criteria

- [x] Clicking on one grocery item opens the details page
- [x] There is a headline "Item Detailspage"
- [x] The grocery item is displayed with its name
- [x] If a grocery item has a note, the note is displayed
- [x] A click on the “back to list” Link returns to the list of all grocery items

## Tasks

- [x] Create the feature branch "product-details-page"
- [x] In the “Product” component, add a Link-element to the `/products/$[id]/index.js` file.
- [x] Create the `/products/[id]/index.js` file, use the router to get the `[id]` from the query and find the grocery product from the `products` array with the matching id. Return the <code>product.name</code> and <code>product.note</code> and a “back to list” link `href=/index.js`.

**Comment by Julia-Pickel** [comment]
Hey @lennart-kaminsky @GoekhanAgkurt @luederb ,

very nice User Story! 🙌

We have a few recommendations for you:
- In your AC you wrote *There is a headline "Product Detailspage"* but your wireframe shows a different headline *"Item detailspage"*
- In your introduction you wrote as a benefit of this User Story that there are detailed information of the product seen. We are wondering why the details page doesn't show details of the specific item. Maybe you can implement some extra information for the user here.

Keep it up Grocery Team 🤙

**Comment by Julia-Pickel** [comment]
Yeah looks good to us !!! 🥳
