### ISSUE TITLE
US - Shopping List Products counter

### ISSUE THREAD

**Issue by lennart-kaminsky** [GoekhanAgkurt/capstone-grocery-app#40]
## Value proposition

As a user
I want to know the number of products in my shopping list
In order to quickly know the dimension of my next shopping trip

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/134974986/c928f862-1e7b-4887-9f1c-8fec7ff59b25)

## Acceptance criteria

- [ ] There is a counter next to the shopping list icon in the navigation bar 
  - [ ] that shows the number of products on the shopping list
  - [ ] that is only displayed when products are on the shopping list  
- [ ] the counter displays the current number of all Products wich are in the shopping list
- [ ] In the store list there is a counter for each store
  - [ ] that is only displayed when products of the Store are on the shopping list 
  - [ ] the counter shows the current number of products that have been assigned to the store and are in the shopping list

## Tasks

- [ ] make a new branch
- [ ] make a new component for the counter
  - [ ] that gets the props `products` and `store`
  - [ ] it returns the counter number depending on the received `store`
- [ ] render the counter component in each store list item and in the nav bar

**Comment by Shahab-Ziaeian** [comment]
Hey grocery-app team! This looks pretty clean and precise to me. Nice User Story 🔥
