### ISSUE TITLE
US - Burger Menu

### ISSUE THREAD

**Issue by lennart-kaminsky** [GoekhanAgkurt/capstone-grocery-app#41]
## Value proposition

As a User i want some information about the Grocery-App 
In order to know more about the team and their spirit.

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/134974986/be76cb68-d006-404c-b286-668767aa8983)

## Acceptance criteria

- [ ] there is a burger icon in the header
- [ ] when clicking the burger icon, a menu opens wich displays links like "Team" or "Project"
- [ ] when the menu is displayed there is a close icon button to close it again. The menu overlaps the header and the navbar
- [ ] When clicking the links in the menu, the user lands on the respective pages
- [ ] The team page displays some information about the Grocery-Team

## Tasks

- [ ] make an new branch
- [ ] make a component "BurgerMenu" wich will render in the Header
- [ ] make a toggleble state `showMenu` so the menu can be rendered conditionally depending on this state
- [ ] create separate pages for the links of the menu content
- [ ] build a gallery wich includes all team members of the grocery app

**Comment by Roland-Hufnagel** [comment]
Looks good 🍌
