### ISSUE TITLE
US - Delete Grocery Product

### ISSUE THREAD

**Issue by GoekhanAgkurt** [GoekhanAgkurt/capstone-grocery-app#5]
## Value proposition

As a user
I want to delete an item from the products list and see the updated list of products
In order to delete products that i don’t want to buy anymore

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/3a697378-3d95-4244-8a36-59a60d2fd993)

## Acceptance criteria

- [ ] Each product on the products list has a little “X”-Button.
- [ ] After clicking the X-button, the confirm and cancel buttons appear. When confirming, the product gets deleted. When clicking cancel both buttons disappear again.
- [ ] The list doesn’t display deleted products

## Tasks

- [ ] Create the feature branch "delete-product"
- [ ] Inside the /index.js,
  - [ ] write a “handleDeleteItem(productToDelete)” function.
  - [ ] The function filters the “products” array so that it only contains the products apart from the “productToDelete” - product.
  - [ ] In the return of the /index.js, give the “Product” component the prop onClick={handleDeleteProduct} 
- [ ] The “Product” component receives the prop {onClick} and returns an “X”-Button that sets a state "showConfirmation" as true.  Depending on the "showConfirmation"-state a div with the confirm or cancel buttons will conditionally be shown. The confirm link gets the property onClick={onClick(product.name)}. The Cancel button sets the "showConfirmation" state to false.

```

**Comment by onemanwenttomow** [comment]
> After clicking the X-button, the confirm or cancel buttons appear. When confirming, the product gets deleted

How is this going to look? What happens when i click cancel?

I think we might need some conditional rendering for the confirm dialog as well as adding this feature to the wireframes. We will probably need to consider if we need to keep track of something in state to determine if the confirm dialog is visible or not.

**Comment by lennart-kaminsky** [comment]
Hey @onemanwenttomow,

those are some really good points. We adjusted our wireframes, acceptance criteria and tasks. ✌
