### ISSUE TITLE
US - Edit Grocery Product

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#6]
## Value proposition

As a user, 
I want to be able to edit the name and note of a specific product
so I can customise the product details based on my preferences or changing needs.	

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/a253f0e1-b362-475b-88da-dbbf628ff86f)

## Acceptance criteria

- [ ] From the details page of a grocery product, there is a visible “Edit” button.
- [ ] Clicking the “Edit” button 
  - [ ] changes the name and note fields to editable input fields.
  - [ ] changes the "<- Back" and "Edit" buttons to "Cancel" and "Submit" buttons.
- [ ] The input fields should be pre-filled with the current name and note of the product to provide a starting point for editing. 
- [ ] The “Submit” button applies the changes of the name and note of the product and changes the form and buttons back to the initial "name" and "note" fields and back to the initial "<- Back" and "Edit" buttons. The submitted changes to the name and / or note should be displayed in the "name" and "note" fields. 
- [ ] the "Cancel" button cancels the editing process displays the initial "<- Back" and "Edit" buttons and the initial "name" and "note" fields with the previous values for the name and note.

## Tasks

- [ ] Inside the `/products/[id]/index.js` file, add an “Edit” button that flips a `isEdit`- state variable from true to false and back. 
- [ ] In the return of the `/products/[id]/index.js` file, ask if the `isEdit` - state is `true` or `false`. 
- [ ] If the `isEdit` - state is `false`, render the current name and note values of the current product and render a "<- Back" and "Edit" button. 
- [ ] If the `isEdit` - state is `true`, render a form with
  - [ ] two input fields for the name and for the note of the grocery product. The input fields have the current value of the grocery product name and note. The name and note are editable. 
  - [ ] a “Submit” button.
  - [ ] the form receives a `handleEditItem` function as the onSubmit value
  - [ ] a “Cancel” link, that sets the `isEdit` - state back to `false` 
- [ ] Write a `handleEditProduct` function that takes an event and id as parameters and 
  - [ ] changes the name and note of the product with the given id of the `products`-array in localStorage to the value of the respective input fields with the help of  `event.target`
  - [ ] switches the `isEdit` state to `false`. 
  - [ ] make sure that the updated name and note is displayed directly after submitting the form

**Comment by NikRoe** [comment]
Hi there,

great work so far 👏 Approved ✅ 

You have an empty code block at the very end of your User Story that you most likely don't want to have there.
It looks to me like this could be due to your [template](https://github.com/GoekhanAgkurt/capstone-grocery-app/issues/1). 

>  make sure that the updated name and note is displayed directly after submitting the form (useEffect?)

You won't need a useEffect here :)

**Comment by luederb** [comment]
Hi @NikRoe 
Thanks a lot for the review and your comment 🙂
Yes, the code block was an artefact from the templated. We removed it. 
Thanks, good to know, that we won't need to use useEffect in this case 🥳👍
