### ISSUE TITLE
US - Add Product and link it to Store

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#7]
## Value proposition

As a user that gets his groceries in more than one store,

I want to be able to add the store, where i can buy the product, to the product information.

so I can use this information to better plan my next shopping trip.

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/c92b05d1-3690-4212-b049-369401b527a4)

## Acceptance criteria

- [ ] While adding a product, the user can select an existing store from a dropdown menu.
- [ ] After clicking on a store, the selected store is shown below the new product name.
- [ ] After clicking the "submit"-button, the updated product list page is displayed.
- [ ] When clicking on a product in the product List and opening the details Page, the selected store is also shown below the headline of the page, which is the product name.

## Tasks

- [ ] Inside the `data.js`, name the current array `products` and create a second array of objects called `stores` with example-stores with the key-values pairs: `name: "store-name"` and `storeId: "random storeId"`.
- [ ] In the `/_app.js` file, create a second localStorage State variable `stores`, that has the `stores` array from the `data.js` file as the initial value and drill the `stores` state down to all pages
- [ ] Inside the form that creates a new product, add a `select input` that displays the names of the `stores` array. 
- [ ] when submitting the form, add the key-value pair `id: "random storeId"` of the selected store to the selected product array of the `products` state array. Afterwards the updated list of products is displayed (the store is not displayed in the list view). 
- [ ] Make the title of the product details page dynamic, so it shows the selected product name. 
- [ ] Below the title, render the selected store of that product with the help of the `find` array-method. 
- [ ] If the product is not linked to a store, render the text "no store selected".

**Comment by mbosselmann** [comment]
Hi Team Grocery App,
your user story looks good! 👍 I just thought that maybe it would be nice to see as a user in the product list itself where to buy the product and not in the details page for a better overview? 🤔 

Happy hacking! 💪
