### ISSUE TITLE
US - Store Details Page

### ISSUE THREAD

**Issue by luederb** [GoekhanAgkurt/capstone-grocery-app#8]
## Value proposition

As a user, 

i want to see the details of one single store in my list 

so i can see detailed information of the store

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/3bf44b54-3672-4cf0-8279-3437be3ca7ec)

## Acceptance criteria

- [ ] Clicking on one store opens the details page with the title "Store Details"
- [ ] The store is displayed with its name
- [ ] A click on the “back to list” button returns to the list of all stores

## Tasks

- [ ] In the “Store” component, add a Link-element to the “/stores/$[id]/index.js file.
- [ ] Create the /stores/[id]/index.js file, use the router to get the [id] from the query and find the store from the “stores” array with the matching id. Return `<p> {store.name} </p>` and a “back to list” link with the href=/stores/index.js. 

```

**Comment by luederb** [comment]
Close issue to get a matching order of user stories in the project board
