### ISSUE TITLE
US - Create new Store

### ISSUE THREAD

**Issue by GoekhanAgkurt** [GoekhanAgkurt/capstone-grocery-app#9]
## Value proposition

As a user
I want to add a new store and have it been listed in my list of stores
In order to expand my possible shopping possibilities

## Description

![Image](https://github.com/GoekhanAgkurt/capstone-grocery-app/assets/136329211/11e7d454-b13b-4652-b5d1-54aba4b2e1cc)

## Acceptance criteria

- [ ] on the Store List page, there is a "+" - Link that brings the user to the page "Add a Store"
- [ ] The user can insert the name of a new store and a note for this store in the "Add Store" form.
- [ ] The Submit button adds the new store with its note to the stores list and brings the user back to the updated "Store List" - page. The new store is listed with its name.
- [ ] The new store can be chosen as a selected store for a new product or when editing an existing product.
- [ ] The Cancel button returns to the Store Liste without adding a new store

## Tasks

- [ ] In the "Store list" page, return a Link  “+ Add new Store” to a new `stores/create.js` file
- [ ] Create the /stores/create.js file and
  - [ ] write a “handleAddStore” function that add the new store infos to the `stores`array 
  - [ ] Return
    - [ ] a form to enter the store data
    - [ ] a “Submit” Button
    - [ ] a “Cancel” - Link to the /stores/index.js page

**Comment by Roland-Hufnagel** [comment]
Good Work! This looks good to me. One Question:

``The new store can be chosen as a selected store for a new product or when editing an existing product.``
Do you need a task for this? Or is it already implemented?

**Comment by lennart-kaminsky** [comment]
Hey @Roland-Hufnagel, thank you! This is actually already implemented in our current version, so no need to worry about it anymore ✌️
